### ISSUE TITLE
[1.9] Crash on startup

### ISSUE THREAD

**Issue by Shadows-of-Fire** [Elecs-Mods/E-Flux#8] opened 2016-04-07 16:17 UTC
E-Flux Beta 124
Forge 12.16.0.1854
ElecCore 1.4.261
http://pastebin.com/Ck5aJXE7

**Comment by TrikSteve** [comment] 2016-04-13 17:07
Same issue

E-Flux Beta 124
Forge 12.16.0.1863
ElecCore 1.4.261
http://pastebin.com/raw/Q66u421z

**Comment by Sasikaa** [comment] 2016-04-23 09:55
The NEW 1.9 elec core is crashing same...
net.minecraftforge.fml.common.LoaderException: java.lang.IllegalArgumentException: Attempted to register a Block with conflicting names. Old: eflux:capacitor New: capacitor
    at net.minecraftforge.fml.common.registry.GameRegistry.registerBlock(GameRegistry.java:492)
    at net.minecraftforge.fml.common.registry.GameRegistry.registerBlock(GameRegistry.java:448)
    at elec332.eflux.util.EnumMachines.init(EnumMachines.java:80)
    at elec332.eflux.init.BlockRegister.init(BlockRegister.java:57)
    at elec332.eflux.EFlux.init(EFlux.java:131)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:560)
    at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:228)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:206)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
    at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:737)
    at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:307)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:513)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:346)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.IllegalArgumentException: Attempted to register a Block with conflicting names. Old: eflux:capacitor New: capacitor
    at net.minecraftforge.fml.common.registry.GameRegistry.registerBlock(GameRegistry.java:471)
    ... 40 more

**Comment by Elec332** [comment] 2016-04-30 11:44
Fixed with latest release

**Closed as completed by Elec332** 2016-04-30 11:44 UTC
