### ISSUE TITLE
 e-flux-1.9-1.0beta.124 crashes dedicated forge server 1.9 build 1811 on startup

### ISSUE THREAD

**Issue by kreezxil** [Elecs-Mods/E-Flux#7] opened 2016-03-27 15:55 UTC
Issue: e-flux-1.9-1.0beta.124 crashes dedicated forge server 1.9 build 1811 on startup

crash report:
https://gist.github.com/7016abb369d20bff861e

fml server latest:
https://gist.github.com/5e968efddec9438ad1cd

**Comment by Elec332** [comment] 2016-03-28 15:02
Duplicate of #4

**Closed as completed** 2017-11-16 13:26 UTC
Labels: bug, duplicate
